os: linux
language: cpp
compiler: g++

matrix:
  include:
    - python: 3.8
branches:
  only:
    - devel
    - /^v\d+\.\d+\.\d+.*$/  # version tags

services:
  - docker
  
notifications:
  email:
    recipients:
      - francesco.ruscelli@iit.it
    on_success: never
    on_failure: always

before_install:
  - rm -rf /opt/pyenv

before_script:
  - echo "Travis tag is $TRAVIS_TAG"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
  - sudo apt update && sudo apt install libgtest-dev libyaml-cpp-dev python3-pip python3-setuptools liburdfdom-dev cmake libeigen3-dev libboost-filesystem-dev libboost-serialization-dev libblas-dev liblapack-dev patchelf python3-venv

script:

  - curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
  - printf '\nyes\n\nyes\n' | bash Mambaforge-$(uname)-$(uname -m).sh
  - FOREST_ARGS="--default-build-type Release --clone-protocol https --verbose -j2"
  - yes Y | mamba env create -f environment.yml
  - sudo chmod +x initial_commands.sh && ./initial_commands.sh
