package:
  name: "horizon"
  version: "0.4.0"

source:
  git_url: https://github.com/ADVRHumanoids/horizon.git
  git_rev: fr_devel

build:
  noarch: python
  number: 0
  script: python3 -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools

about:
  home: https://github.com/ADVRHumanoids/horizon.git
  summary: "Trajectory optimization framework tailored for robotics applications based on CasADi"

extra:
  recipe-maintainers:
    - francesco_ruscelli
