name: caskin
channels:
- conda-forge
- robostack
- francesco_ruscelli
dependencies:
- python=3.8
- ipython
- casadi
- ros-noetic-pinocchio
- francesco_ruscelli::casadi_kin_dyn
#- francesco_ruscelli::casadi-horizon
#- pip
#- pip:
# - casadi-horizon

