name: caskin
channels:
- conda-forge
- robostack
- francesco_ruscelli
dependencies:
- python=3.7
- casadi
# - francesco_ruscelli::casadi_kin_dyn=0.0.2
#- francesco_ruscelli::casadi-horizon
#- pip
#- pip:
# - casadi-horizon

