name: kindyn
channels:
- conda-forge
- robostack
dependencies:
- python=3.8
- nodejs
- casadi
- hpp-pinocchio # (necessary for hpp-flc that the branch collision uses)
- pybind11
- urdfdom
- cmake
- conda-build
- conda-verify
- anaconda-client
- ros-noetic-ros-base
- gxx_linux-64  # required for a bug in letsee (which is actually not necessary)
# - ros-noetic-pinocchio # not required as hpp-pinocchio is there already
# - eigenpy # not required I believe 

